name: Post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  post:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}

      - name: Post
        run: npm run post
        env:
          # openai
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # slack
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_OAUTH_TOKEN: ${{ secrets.SLACK_OAUTH_TOKEN }}
